config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'workouts#index'

  resources :workouts
  resources :workout_sets
  resources :exercises
  resources :routines

end

app/models/workout.rb
class Workout < ApplicationRecord

  has_many :workout_sets, ->{ order(:id) }, dependent: :delete_all
  has_many :exercises, through: :workout_sets

  alias_attribute :sets, :workout_sets

  def muscle_groups
    #sets.includes(exercise: :muscle).pluck(:muscle_group).sort.uniq
    sets.collect{|s| s.exercise.muscle.muscle_group}.sort.uniq
  end

  def total_weight_per_group
    h = Hash.new{|h,k|h[k]=0}
    workout_sets.each{|ws| h[ws.exercise.muscle.muscle_group] += ws.total_weight}
    h
  end

  def total_weight
    sets.reject{|s| s.warmup? }.sum(&:total_weight)
  end

  def total_reps
    sets.exists? ? sets.collect_concat(&:reps).sum : 0
  end

  def duration
    sets.exists? ? sets.last.created_at - created_at : 0
  end

  def rate # reps per minute
    sets.exists? ? total_reps / duration * 60 : 0
  end

  def intensity
    sets.exists? ? total_weight / total_reps : 0
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController


  def index
    workouts = Workout.includes(workout_sets: {exercise: :muscle}).order('id desc').limit(50)
    @workouts = {}
    workouts.each{|w| w.muscle_groups.each{|mg| @workouts[mg] ||= w } }
  end

  def create
    @workout = Workout.new
    @workout.save
    redirect_to @workout
  end

  def show
    @workout = Workout.includes(exercises: :equipment).find(show_params[:id])
    @previous_set = @workout.sets&.last
    @previous_set.notes = '' if @previous_set
# TODO maybe if workout.date < today skip previous?
    @combined = Hash.new{|k,v|k[v]=[]}
    if ( @workout.muscle_groups )
#@previous_workout = Hash{|h,k|h[k]=
      @previous_workouts = {}
      @workout.muscle_groups.each do |mg|
        @previous_workouts[mg.name] = Workout.joins(workout_sets: {exercise: :muscle}).where(muscles: { muscle_group_id: mg.id }).where('workouts.id < ?', @workout.id).last
      end
      @previous_workout = Workout.joins(workout_sets: {exercise: :muscle}).where(muscles: { muscle_group_id: @workout.muscle_groups.map(&:id) }).where('workouts.id < ?', @workout.id).last

      if @previous_workout
        @max_sets = @workout.sets.size > @previous_workout.sets.size ? @workout.sets.size : @previous_workout.sets.size
        0.upto(@max_sets) do |i|
          @combined[:current] << @workout.sets[i] if i < @workout.sets.size
          @combined[:previous] << @previous_workout.sets[i] if i < @previous_workout.sets.size
        end
      else
      @combined[:current] = @workout.sets
      @combined[:previous] = []
      @max_sets = @workout.sets.size
      end
    else
      @combined[:current] = @workout.sets
      @combined[:previous] = []
      @max_sets = @workout.sets.size
    end



    @set = WorkoutSet.new(@workout.sets&.last&.attributes)
  end
  
  def show_params
    params.permit(:id)
  end
  
end

app/helpers/workouts_helper.rb
module WorkoutsHelper

  def hours(seconds)
    "#{(seconds / 3600).to_i}h " if seconds >= 3600
  end

  def minutes(seconds)
    %Q|#{(seconds % 3600).to_i / 60}m| if seconds % 60 != 0
  end

  def remaining_seconds(seconds)
  end

  def format_seconds(seconds)
    "#{hours(seconds)}#{minutes(seconds)}" if seconds
  end

end

app/views/workouts/_sets.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Exercise</th>
      <th>Weight</th>
      <th>Reps</th>
      <th>Total Weight</th>
    </tr>
  </thead>



  <tbody>

    <% 0.upto(@max_sets) do |i| %>
      <% set = @combined[:current][i] if i < @workout.sets.size %>
      <% if set %>
      <tr>
        <td><%= link_to set.exercise.title, edit_workout_set_path(set) %></td>
        <td><%= set.weights&.map(&:round).join(', ') %></td>
        <td><%= set.reps&.map(&:round).join(', ') %></td>
        <td><%= set.total_weight&.round %></td>
      </tr>
      <% end %>
      <% previous_set = @combined[:previous][i] if @previous_workout and i < @previous_workout.sets.size %>
      <% if previous_set %>
      <tr class="previous-set">
        <td><div><%= previous_set.exercise.title %></div></td>
        <td><div><%= previous_set.weights&.map(&:round).join(', ') %></div></td>
        <td><div><%= previous_set.reps&.map(&:round).join(', ') %></div></td>
        <td><div><%= previous_set.total_weight&.round %></div></td>
        <%#= fa_icon "info-circle" unless previous_set.notes.blank? %></i>
      </tr>
      <tr class="previous-set">
        <td></td>
        <td style="column-span: all"><div><%= previous_set.notes %></div></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/workouts/_timer.html.erb
<div id="timer">

  <h3></h3>

</div>

<% if @set.created_at&.today? %>
<script type="text/javascript">

var english_voice;
// list of languages is probably not loaded, wait for it
if(window.speechSynthesis.getVoices().length == 0) {
	window.speechSynthesis.addEventListener('voiceschanged', function() {
		textToSpeech();
	});
}
else {
	// languages list available, no need to wait
	textToSpeech()
}

function textToSpeech() {
	// get all voices that browser offers
	var available_voices = window.speechSynthesis.getVoices();

  // find voice by language locale "en-US"
	// if not then select the first voice
	for(var i=0; i<available_voices.length; i++) {
		if(available_voices[i].lang === 'en-US') {
			english_voice = available_voices[i];
			break;
		}
	}
	if(english_voice === '')
		english_voice = available_voices[0];

}

function say(words){
  var utter = new SpeechSynthesisUtterance();
	utter.rate = 1;
  utter.pitch = 0.5;
  utter.text = words;
  utter.voice = english_voice;
  window.speechSynthesis.speak(utter);
}

</script>



<script type="text/javascript">
  var muted = false;
  var startTime = Date.parse("<%= @set.created_at.iso8601 %>");
  var totalSeconds = 0;

  $(document).keydown(function(e) {
    if (e.which === 77){
      muted = !muted; }
  });

  if (!isNaN(startTime)){
    var timeString = "";

    setInterval(function() {

      totalSeconds = Math.floor((new Date - startTime) / 1000);
      if ( totalSeconds > 600 ){
        return; }

      var minutes = Math.floor(totalSeconds / 60)
      var seconds = totalSeconds % 60;
      if ( totalSeconds > 60 ){
        timeString = minutes + " minutes " + seconds + " seconds";
        $("#timer h3").text(timeString);
      }
      else {
        timeString = totalSeconds + " seconds";
        $("#timer h3").text(timeString); }
    }, 1000);

    var talker = setInterval(function() {
      if (totalSeconds > 600){ clearInterval(talker) }
      if (! muted) {
        var lastChar = timeString[timeString.length -1];
        timeString = timeString + (lastChar === 's' ? ' have' : ' has') + ' passed'
        say(timeString); }
    }, 60000);

  }
</script>
<% end %>

app/views/workouts/index.html.erb
<br>
<%= link_to 'New', url_for(controller: 'workouts', action: 'create'), method: :post, style: 'font-size: x-large' %>

<br><br>

<table class="table">
  <thead>
    <tr>
      <th>Time Since Last Worked</th>
      <th>Muscle Groups</th>
      <th>Total Weight</th>
    </tr>
  </thead>
  <tbody>
<% @workouts.sort_by{|k,v| v.id}.each do |muscle_group,workout| %>
    <tr>
      <td>
        <%= link_to time_ago_in_words(workout.created_at), workout_path(workout) %>
      </td>
      <td>
        <%= muscle_group.name %><%= raw("<span style='font-style: italic'>, #{(workout.muscle_groups.map(&:name) - [muscle_group.name]).join(', ')}</span>") if workout.muscle_groups.size > 1 %>
      </td>
      <td>
        <% totals = workout.muscle_groups.collect{|mg| workout.total_weight_per_group[mg].round} %>
        <%= totals.join(', ') %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/workouts/show.html.erb
  <div class="col-xs-3 pull-left">
    <div class="row" style="margin-top: -20px">
      <%= render partial: 'workout_sets/form' %>
    </div>
    <div class="row" style="margin-top: 40px">
      <%= render 'timer' %>
    </div>
  </div>

  <div class="col-xs-1"></div>

  <div class="col-xs-4 pull-left">
    <div class="row" style="margin-top: 10px">
      <%= render 'sets' %>
    </div>
  </div>


  <div class="col-xs-2 pull-right">
    <div class="row">
      <%= @workout.total_weight.round %>/<%= @previous_workout&.total_weight&.round %> lbs
    </div>
    <div class="row">
      <%= @workout.sets&.count %>/<%= @previous_workout&.sets&.count %> sets
    </div>
    <div class="row">
      <%= @workout.rate.round(2) %> / <%= @previous_workout&.rate&.round(2) %> reps/minute
    </div>
    <div class="row">
      <%= @workout.intensity.round(2) %> / <%= @previous_workout&.intensity&.round(2) %> lbs/rep
    </div>
    <div class="row">
      <%= format_seconds(@workout.duration) %> / <%= format_seconds(@previous_workout&.duration) %>
    </div>
  </div>