config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'workouts#index'

  resources :workouts
  resources :workout_sets
  resources :exercises
  resources :routines

end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :muscle_group
  has_many :exerciess, through: :routine_exercise
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController


  def index
    @routines = Routine.all
  end

  def new
    @routine = Routine.new
  end

  def create
    @routine = Routine.new
  end

  def show
    @routine = Routine.find(show_params[:id])
  end
  
  def show_params
    params.permit(:id)
  end
  
end

app/views/routines/_form.html.erb
<%= form_for @routine do |rf| %>

  <div class="form-group">
    <%= rf.label :name %>
    <%= rf.text_field :name, class: 'form-control col-xs-6' %>
  </div>

  <div class="form-group">
    <%= rf.label :link %>
    <%= rf.text_field :link, class: 'col-xs-6 form-control', tabindex: 1 %>
  </div>

  <div class="form-group">
    <%= rf.label :target_muscle_group %>
    <%= rf.select :muscle_group_id, Muscle.order(:name).collect{|m|[m.name, m.id]}, {}, class: 'cols-xs-6 form-control' %>
  </div>

  <br>
  <br>

  <%= field_set_tag('Set List', class: 'form-group') do %>
    <%= rf.fields_for :exercises do |ef| %>
    <div class="form-group">
      <%= ef.label :exercise %>
      <%= ef.select :exercise_id, grouped_options_for_select(Exercise.grouped_by_muscle_group.sort_by{|k,v| k}), {},
          { onChange: 'javascript: $("#exerciseLink").attr("href", ( exerciseLinks[$("#workout_set_exercise_id").val()] ) )',
          class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= ef.label :sets %><br>
      <%= ef.text_field :sets %>
    </div>

    <% end %>
  <% end %> <%# fieldset %>

  <%= rf.submit class: 'pull-right' %>
<% end %>

app/views/routines/edit.html.erb
<div class="row">
  <div class="col-xs-4">
    <%= render 'form', type: 'Update' %>
  </div>
</div>

app/views/routines/index.html.erb
<h3>Routines</h3>

<br>

<%# @routines.sort_by{|e| [e.muscle.name, e.title]}.each do |exercise| %>
<% @routines.each do |routine| %>

<div class="row" style="line-height: 30px">
  <div class="col-xs-3"><%#= link_to "#{exercise.equipment&.name&.titleize} #{exercise.name}", edit_exercise_path(exercise) %></div>
  <div class="col-xs-1"><%= routine.name %></div>
  <div class="col-xs-1"><%#= routine.multiplier %></div>
  <div class="colx-xs-1">

    <%#= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, exercise_path(exercise), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn' %>

    
  </div>
</div>

<% end %>

<br>

<%= link_to 'New', new_routine_url, class: 'btn' %>

app/views/routines/new.html.erb
<div class="row">
  <div class="col-sm-4">

    <h3>New Routine</h3>
    <br>
    <%= render 'form' %>
  </div>
</div>