config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'workouts#index'

  resources :workouts
  resources :workout_sets
  resources :exercises
  resources :routines

end

app/models/workout_set.rb
class WorkoutSet < ApplicationRecord

  belongs_to :exercise
  belongs_to :workout

  def total_weight
    reps.each_with_index.map{|rep,i| rep * weights[i] * multiplier }.sum
  end

  def multiplier
    exercise.multiplier || 1
  end

  def load_exercise
    @exercise = Rails.cache.fetch(exercise_id){ Exercise.find(exercise_id) } unless exercise_id.blank?
  end

  def warmup?
    warmup
  end

  def pr_by_weight

  end

  def pr_by_volume

  end


end

app/controllers/workout_sets_controller.rb
class WorkoutSetsController < ApplicationController


  def create
    permitted = create_params
    permitted[:reps] = permitted[:reps].split.map(&:to_i)
    weights = permitted[:weights].split.map(&:to_f)
    if weights.size < permitted[:reps].size
      if weights.size == 0
        weights = permitted[:reps].map{0}
      else
        weights = weights + reps[0..weights.size-1].map{weights.last}.map{weights.last}
      end
    end
    permitted[:weights] = weights
    set = WorkoutSet.new(permitted)
    set.save

    workout = Workout.find(workout_param[:id])

    # if workout.muscle_groups.nil? or  workout.muscle_groups.empty? #or (! workout.muscle_groups.any?{|mg| mg == set.exercise.muscle_group} )
    #   workout.muscle_groups ||= []
    #   workout.muscle_groups << set.exercise.muscle.muscle_group
    #   workout.save
    # end
    redirect_to workout
  end

  def edit
    @set = WorkoutSet.find(set_id_param)
    @exercises = Exercise.all
  end
  def update
    @set = WorkoutSet.find(set_id_param)
    permitted = update_params
    permitted[:reps] = permitted[:reps].split.map(&:to_i)
    permitted[:weights] = permitted[:weights].split.map(&:to_f)
    
    @set.update_attributes(permitted)
    redirect_to Workout.find(@set.workout_id)
  end

  def destroy
    WorkoutSet.find(set_id_param).destroy
    redirect_to workouts_path
  end


  def create_params
    params.require(:workout_set).permit(:exercise_id, :reps, :weights, :notes, :warmup).merge(workout_id: workout_param[:id])
  end
  def update_params
    params.require(:workout_set).permit(:id, :exercise_id, :reps, :weights, :notes, :warmup)
  end
  def set_id_param
    params.require(:id)
  end
                     
  def workout_param
    params.require(:workout).permit(:id)
  end
  
end

app/helpers/workout_sets_helper.rb
module WorkoutSetsHelper
end

app/views/workout_sets/_form.html.erb
<script>
  var exerciseLinks = <%= Hash[Exercise.all.map{|ex| [ex.id, ex.link]}].to_json.html_safe%>;
</script>



<%= form_for @set, html: {style:"margin-top: 40px"} do |f| %>

  <%= hidden_field :workout, :id %>
  <div class="form-group">
    <%= f.label :exercise_id, 'Exercise' %>
    <%= f.select :exercise_id, grouped_options_for_select(Exercise.grouped_by_muscle_group.sort_by{|k,v| k}, @set.exercise_id), {},
                 { onChange: 'javascript: $("#exerciseLink").attr("href", ( exerciseLinks[$("#workout_set_exercise_id").val()] ) )',
                   class: 'form-control' } %>
    <a href="#" id="exerciseLink" target='_new' style="disply: inline-block" class="pull-right btn">Link</a>
  </div>

  <div class="form-group">
    <%= f.label :reps, 'Weights' %>
    <%= f.text_field :weights, class: 'form-control', value: @set&.weights&.map{|w| (w.to_i == w.to_f) ? w.to_i : w.to_f}, tabIndex: 1  %>
  </div>

  <div class="form-group">
    <%= f.label :reps, 'Reps' %>
    <%= f.text_field :reps, class: 'form-control', tabIndex: 2 %>
  </div>  

  <div class="form-group">
    <%= f.label :notes, 'Notes' %>
    <%= f.text_area :notes, class: 'form-control', tabIndex: 3 %>
  </div>

  <div class="form-group">
    <%= f.label :warmup, 'Warmup?' do %>
      Warmup? <%= f.check_box :warmup, tabIndex: 5, checked: @previous_set.nil? %>
    <% end %>
  </div>

  <%= f.submit 'Add', tabIndex: 4 %>
  
<% end %>

<% unless @workout %>
<div class="row">
  <div class="col-xs-6 pull-right">
    <%= link_to 'Delete', workout_set_path(@set), method: :delete, data: {confirm: 'Are you sure?'} if @set.id %>
  </div>
</div>
<% end %>

<script>
  $("#exerciseLink").attr("href", ( exerciseLinks[$("#workout_set_exercise_id").val()] ) );
</script>

app/views/workout_sets/edit.html.erb
<%= render 'form' %>